import Head from 'next/head'
import { Box } from '@chakra-ui/react'
import cookie from 'cookie'

export default function Home() {
    return (
        <Box>
            <Head>
                <title>Contratos</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box>
                index
            </Box>
        </Box>
    )
}

export function getServerSideProps({ req }) {
    const cookies = cookie.parse(req.headers.cookie || '')

    if (cookies.token)
        return {
            redirect: {
                destination: '/home',
                permanent: false
            }
        }

    return {
        props: {}
    }
}